const fs = require('fs');
const h = fs.readFileSync('dist/index.html', 'utf8');
const all = (re) => h.match(re) || [];
console.log(all(/<title>[\s\S]*?<\/title>/g).join('\n'));
console.log(all(/<meta name="description"[^>]*>/g).join('\n'));
console.log(all(/<link rel="canonical"[^>]*>/g).join('\n'));
console.log(all(/<link rel="alternate"[^>]*>/g).join('\n'));
console.log(all(/<meta property="og:site_name"[^>]*>/g).join('\n'));
console.log(all(/<h1[\s\S]*?<\/h1>/g).join('\n'));
console.log('stay section:', h.includes('id="stay"'), '| naver map:', h.includes('map.naver.com'), '| google dir:', h.includes('maps/search/?api=1'));
const ld = JSON.parse(h.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)[1]);
const a = ld['@graph'][0];
console.log('types:', JSON.stringify(a['@type']), '| hasMap:', a.hasMap);
console.log('hours:', JSON.stringify(a.openingHoursSpecification));
console.log('faq count:', ld['@graph'][1].mainEntity.length);
console.log(ld['@graph'][1].mainEntity.slice(-3).map((q) => q.name).join(' / '));
